// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'modules/root/models/entry.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2921322981885767544),
    name: 'Entry',
    lastPropertyId: const obx_int.IdUid(13, 1258633182273164030),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2406565493571667038),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7038988196758643461),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 4574716066135910415),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4237884650794000427),
        name: 'type',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(2, 508243600145150473),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2245908109073345536),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 593944210368775336),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8608867439557255018),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 296584792822316957),
        name: 'updatedAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(3, 8002253217635285319),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1373196908836038075),
        name: 'entryDate',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(4, 179621800447538974),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5450095972211117604),
        name: 'deletedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2582403221465750953),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2334986041458246311),
        name: 'isPinned',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3714216802790571302),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1258633182273164030),
        name: 'revision',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 2921322981885767544),
    lastIndexId: const obx_int.IdUid(4, 179621800447538974),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [2612930520608178848],
    retiredIndexUids: const [],
    retiredPropertyUids: const [7504485300965488326, 5395399737422201148],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Entry: obx_int.EntityDefinition<Entry>(
      model: _entities[0],
      toOneRelations: (Entry object) => [],
      toManyRelations: (Entry object) => {},
      getId: (Entry object) => object.id,
      setId: (Entry object, int id) {
        object.id = id;
      },
      objectToFB: (Entry object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = object.title == null
            ? null
            : fbb.writeString(object.title!);
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addInt64(2, object.type);
        fbb.addOffset(3, titleOffset);
        fbb.addOffset(4, contentOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.entryDate?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.deletedAt?.millisecondsSinceEpoch);
        fbb.addBool(9, object.isFavorite);
        fbb.addBool(10, object.isPinned);
        fbb.addBool(11, object.isArchived);
        fbb.addInt64(12, object.revision);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final entryDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final deletedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final typeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          isUtc: true,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          isUtc: true,
        );
        final entryDateParam = entryDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(entryDateValue, isUtc: true);
        final deletedAtParam = deletedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(deletedAtValue, isUtc: true);
        final isFavoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final isPinnedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final revisionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final object = Entry(
          id: idParam,
          uuid: uuidParam,
          type: typeParam,
          title: titleParam,
          content: contentParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          entryDate: entryDateParam,
          deletedAt: deletedAtParam,
          isFavorite: isFavoriteParam,
          isPinned: isPinnedParam,
          isArchived: isArchivedParam,
          revision: revisionParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Entry] entity fields to define ObjectBox queries.
class Entry_ {
  /// See [Entry.id].
  static final id = obx.QueryIntegerProperty<Entry>(_entities[0].properties[0]);

  /// See [Entry.uuid].
  static final uuid = obx.QueryStringProperty<Entry>(
    _entities[0].properties[1],
  );

  /// See [Entry.type].
  static final type = obx.QueryIntegerProperty<Entry>(
    _entities[0].properties[2],
  );

  /// See [Entry.title].
  static final title = obx.QueryStringProperty<Entry>(
    _entities[0].properties[3],
  );

  /// See [Entry.content].
  static final content = obx.QueryStringProperty<Entry>(
    _entities[0].properties[4],
  );

  /// See [Entry.createdAt].
  static final createdAt = obx.QueryDateProperty<Entry>(
    _entities[0].properties[5],
  );

  /// See [Entry.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Entry>(
    _entities[0].properties[6],
  );

  /// See [Entry.entryDate].
  static final entryDate = obx.QueryDateProperty<Entry>(
    _entities[0].properties[7],
  );

  /// See [Entry.deletedAt].
  static final deletedAt = obx.QueryDateProperty<Entry>(
    _entities[0].properties[8],
  );

  /// See [Entry.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<Entry>(
    _entities[0].properties[9],
  );

  /// See [Entry.isPinned].
  static final isPinned = obx.QueryBooleanProperty<Entry>(
    _entities[0].properties[10],
  );

  /// See [Entry.isArchived].
  static final isArchived = obx.QueryBooleanProperty<Entry>(
    _entities[0].properties[11],
  );

  /// See [Entry.revision].
  static final revision = obx.QueryIntegerProperty<Entry>(
    _entities[0].properties[12],
  );
}
